/* Generated by re2c 4.0.1 */
#line 1 "tokenizer.re"
// Compile with:
// re2c -b tokenizer.re -o tokenizer.cpp

#include <stdbool.h>

#include "tokenizer.h"


#define RET(x) \
    *token_type=x; \
    *position = cur-string; \
    return;

void tokenizer_get_next_token(const unsigned char *string,
        uint64_t *position, TokenType *token_type)
{
    const unsigned char *cur = string + *position;
    while (true) {
        /*
        Re2c has excellent documentation at:

        https://re2c.org/manual/manual_c.html

        The first paragraph there explains the basics:

        * If multiple rules match, the longest match takes precedence
        * If multiple rules match the same string, the earlier rule takes
          precedence
        * Default rule `*` should always be defined, it has the lowest priority
          regardless of its place and matches any code unit
        * We use the "Sentinel character" method for end of input:
            * The end of the input text is denoted with a null character \x00
            * Thus the null character cannot be part of the input otherwise
            * There is one rule to match \x00 to end the parser
            * No other rule is allowed to match \x00, otherwise the re2c block
              would parse past the end of the string and segfaults
            * A special case of the previous point are negated character
              ranges, such as [^"\x00], where one must include \x00 in it to
              ensure this rule does not match \x00 (all other rules simply do
              not mention \x00)
            * See the "Handling the end of input" section in the re2c
              documentation for more info

        The re2c block interacts with the rest of the code via just one pointer
        variable `cur`. On entering the re2c block, the `cur` variable must
        point to the first character of the token to be tokenized by the block.
        The re2c block below then executes on its own until a rule is matched:
        the action in {} is then executed. In that action `cur` points to the
        first character of the next token.

        Before the re2c block we save the current `cur` into `tok`, so that we
        can use `tok` and `cur` in the action in {} to extract the token that
        corresponds to the rule that got matched:

        * `tok` points to the first character of the token
        * `cur-1` points to the last character of the token
        * `cur` points to the first character of the next token
        * `cur-tok` is the length of the token

        In the action, we do one of:

        * call `continue` which executes another cycle in the for loop (which
          will parse the next token); we use this to skip a token
        * call `return` which returns from this function; we return a token

        In both cases, `cur` points to first character of the next
        token, which becomes `tok` at the next iteration of the loop (either
        right away after `continue` or after the `lex` function is called again
        after `return`).

        See the manual for more details.
        */


        // These two variables are needed by the re2c block below internally,
        // initialization is not needed. One can think of them as local
        // variables of the re2c block.
        const unsigned char *mar, *ctxmar;
        
#line 83 "tokenizer.c"
{
	unsigned char yych;
	unsigned int yyaccept = 0;
	static const unsigned char yybm[256] = {
		  0,  64,  64,  64,  64,  64,  64,  64,
		 64,  80,  64,  80,  64,  80,  64,  64,
		 64,  64,  64,  64,  64,  64,  64,  64,
		 64,  64,  64,  64,  64,  64,  64,  64,
		 80,  64,   0,  64,  64,  64,  64,  64,
		 64,  64,  64,  64,  64,  64,  64,  64,
		224, 224, 224, 224, 224, 224, 224, 224,
		224, 224,  64,  64,  64,  64,  64,  64,
		 64,  96,  96,  96,  96,  96,  96,  96,
		 96,  96,  96,  96,  96,  96,  96,  96,
		 96,  96,  96,  96,  96,  96,  96,  96,
		 96,  96,  96,  64,  64,  64,  64,  96,
		 64,  96,  96,  96,  96,  96,  96,  96,
		 96,  96,  96,  96,  96,  96,  96,  96,
		 96,  96,  96,  96,  96,  96,  96,  96,
		 96,  96,  96,  64,  64,  64,  64,  64,
		 64,  64,  64,  64,  64,  64,  64,  64,
		 64,  64,  64,  64,  64,  64,  64,  64,
		 64,  64,  64,  64,  64,  64,  64,  64,
		 64,  64,  64,  64,  64,  64,  64,  64,
		 64,  64,  64,  64,  64,  64,  64,  64,
		 64,  64,  64,  64,  64,  64,  64,  64,
		 64,  64,  64,  64,  64,  64,  64,  64,
		 64,  64,  64,  64,  64,  64,  64,  64,
		 64,  64,  64,  64,  64,  64,  64,  64,
		 64,  64,  64,  64,  64,  64,  64,  64,
		 64,  64,  64,  64,  64,  64,  64,  64,
		 64,  64,  64,  64,  64,  64,  64,  64,
		 64,  64,  64,  64,  64,  64,  64,  64,
		 64,  64,  64,  64,  64,  64,  64,  64,
		 64,  64,  64,  64,  64,  64,  64,  64,
		 64,  64,  64,  64,  64,  64,  64,  64
	};
	yych = *cur;
	if (yybm[0+yych] & 16) goto yy4;
	switch (yych) {
		case 0x00: goto yy1;
		case '\t':
		case '\n': goto yy5;
		case ' ':
		case '!': goto yy6;
		case '"': goto yy7;
		case '#': goto yy8;
		case '$': goto yy9;
		case '%': goto yy10;
		case '(': goto yy12;
		case ')': goto yy13;
		case '*': goto yy14;
		case '+': goto yy15;
		case ',': goto yy16;
		case '-': goto yy17;
		case '.': goto yy18;
		case '/': goto yy20;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy21;
		case ':': goto yy22;
		case ';': goto yy23;
		case '<': goto yy24;
		case '=': goto yy25;
		case '>': goto yy26;
		case '@': goto yy27;
		case 'A':
		case 'a': goto yy29;
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'x':
		case 'y':
		case 'z': goto yy31;
		case 'W':
		case 'w': goto yy33;
		case '[': goto yy34;
		case ']': goto yy35;
		case '^': goto yy36;
		case '{': goto yy37;
		case '|': goto yy38;
		case '}': goto yy39;
		default: goto yy2;
	}
yy1:
	++cur;
#line 103 "tokenizer.re"
	{ RET(TK_EOF) }
#line 222 "tokenizer.c"
yy2:
	++cur;
yy3:
#line 102 "tokenizer.re"
	{ RET(TK_ERROR) }
#line 228 "tokenizer.c"
yy4:
	yych = *++cur;
	if (yybm[0+yych] & 16) goto yy4;
#line 104 "tokenizer.re"
	{ RET(TK_WHITESPACE) }
#line 234 "tokenizer.c"
yy5:
	++cur;
#line 105 "tokenizer.re"
	{ RET(TK_NEWLINE) }
#line 239 "tokenizer.c"
yy6:
	++cur;
#line 121 "tokenizer.re"
	{ RET(TK_EXCLAMATION) }
#line 244 "tokenizer.c"
yy7:
	yyaccept = 0;
	yych = *(mar = ++cur);
	if (yych <= 0x00) goto yy3;
	goto yy41;
yy8:
	++cur;
#line 123 "tokenizer.re"
	{ RET(TK_HASH) }
#line 254 "tokenizer.c"
yy9:
	++cur;
#line 122 "tokenizer.re"
	{ RET(TK_DOLLAR) }
#line 259 "tokenizer.c"
yy10:
	yych = *++cur;
	if (yybm[0+yych] & 128) goto yy44;
	if (yych <= '^') {
		if (yych <= '@') goto yy11;
		if (yych <= 'Z') goto yy46;
	} else {
		if (yych == '`') goto yy11;
		if (yych <= 'z') goto yy46;
	}
yy11:
#line 130 "tokenizer.re"
	{ RET(TK_PERCENT) }
#line 273 "tokenizer.c"
yy12:
	++cur;
#line 113 "tokenizer.re"
	{ RET(TK_LPAREN) }
#line 278 "tokenizer.c"
yy13:
	++cur;
#line 114 "tokenizer.re"
	{ RET(TK_RPAREN) }
#line 283 "tokenizer.c"
yy14:
	++cur;
#line 132 "tokenizer.re"
	{ RET(TK_STAR) }
#line 288 "tokenizer.c"
yy15:
	++cur;
#line 124 "tokenizer.re"
	{ RET(TK_PLUS) }
#line 293 "tokenizer.c"
yy16:
	++cur;
#line 131 "tokenizer.re"
	{ RET(TK_COMMA) }
#line 298 "tokenizer.c"
yy17:
	yych = *++cur;
	if (yych == '>') goto yy47;
#line 125 "tokenizer.re"
	{ RET(TK_MINUS) }
#line 304 "tokenizer.c"
yy18:
	yych = *++cur;
	if (yych <= '/') goto yy19;
	if (yych <= '9') goto yy48;
yy19:
#line 136 "tokenizer.re"
	{ RET(TK_DOT) }
#line 312 "tokenizer.c"
yy20:
	yych = *++cur;
	if (yych == '/') goto yy50;
#line 129 "tokenizer.re"
	{ RET(TK_SLASH) }
#line 318 "tokenizer.c"
yy21:
	yyaccept = 0;
	yych = *(mar = ++cur);
	if (yych <= '-') {
		if (yych <= '\v') {
			if (yych == '\t') {
				ctxmar = cur;
				goto yy51;
			}
			if (yych <= '\n') goto yy3;
			ctxmar = cur;
			goto yy51;
		} else {
			if (yych <= '\r') {
				if (yych <= '\f') goto yy3;
				ctxmar = cur;
				goto yy51;
			} else {
				if (yych == ' ') {
					ctxmar = cur;
					goto yy51;
				}
				goto yy3;
			}
		}
	} else {
		if (yych <= 'E') {
			if (yych <= '/') {
				if (yych <= '.') goto yy48;
				goto yy3;
			} else {
				if (yych <= '9') goto yy52;
				if (yych <= 'C') goto yy3;
				goto yy53;
			}
		} else {
			if (yych <= 'e') {
				if (yych <= 'c') goto yy3;
				goto yy53;
			} else {
				if (yych == 'x') goto yy54;
				goto yy3;
			}
		}
	}
yy22:
	++cur;
#line 127 "tokenizer.re"
	{ RET(TK_COLON) }
#line 368 "tokenizer.c"
yy23:
	++cur;
#line 128 "tokenizer.re"
	{ RET(TK_SEMICOLON) }
#line 373 "tokenizer.c"
yy24:
	++cur;
#line 119 "tokenizer.re"
	{ RET(TK_LANGLE) }
#line 378 "tokenizer.c"
yy25:
	++cur;
#line 126 "tokenizer.re"
	{ RET(TK_EQUAL) }
#line 383 "tokenizer.c"
yy26:
	++cur;
#line 120 "tokenizer.re"
	{ RET(TK_RANGLE) }
#line 388 "tokenizer.c"
yy27:
	yych = *++cur;
	if (yych <= '^') {
		if (yych <= '@') goto yy28;
		if (yych <= 'Z') goto yy56;
	} else {
		if (yych == '`') goto yy28;
		if (yych <= 'z') goto yy56;
	}
yy28:
#line 134 "tokenizer.re"
	{ RET(TK_AT) }
#line 401 "tokenizer.c"
yy29:
	yyaccept = 1;
	yych = *(mar = ++cur);
	if (yych <= 'L') {
		if (yych == 'B') goto yy59;
		if (yych <= 'K') goto yy32;
		goto yy60;
	} else {
		if (yych <= 'b') {
			if (yych <= 'a') goto yy32;
			goto yy59;
		} else {
			if (yych == 'l') goto yy60;
			goto yy32;
		}
	}
yy30:
#line 142 "tokenizer.re"
	{ RET(TK_NAME) }
#line 421 "tokenizer.c"
yy31:
	yyaccept = 1;
	yych = *(mar = ++cur);
yy32:
	if (yybm[0+yych] & 32) goto yy31;
	if (yych == '.') goto yy58;
	goto yy30;
yy33:
	yyaccept = 1;
	yych = *(mar = ++cur);
	if (yych == 'R') goto yy61;
	if (yych == 'r') goto yy61;
	goto yy32;
yy34:
	++cur;
#line 115 "tokenizer.re"
	{ RET(TK_LBRACKET) }
#line 439 "tokenizer.c"
yy35:
	++cur;
#line 116 "tokenizer.re"
	{ RET(TK_RBRACKET) }
#line 444 "tokenizer.c"
yy36:
	++cur;
#line 135 "tokenizer.re"
	{ RET(TK_CARET) }
#line 449 "tokenizer.c"
yy37:
	++cur;
#line 117 "tokenizer.re"
	{ RET(TK_LBRACE) }
#line 454 "tokenizer.c"
yy38:
	++cur;
#line 133 "tokenizer.re"
	{ RET(TK_VBAR) }
#line 459 "tokenizer.c"
yy39:
	++cur;
#line 118 "tokenizer.re"
	{ RET(TK_RBRACE) }
#line 464 "tokenizer.c"
yy40:
	yych = *++cur;
yy41:
	if (yybm[0+yych] & 64) goto yy40;
	if (yych >= 0x01) goto yy43;
yy42:
	cur = mar;
	if (yyaccept <= 3) {
		if (yyaccept <= 1) {
			if (yyaccept == 0) goto yy3;
			else goto yy30;
		} else {
			if (yyaccept == 2) goto yy49;
			else goto yy55;
		}
	} else {
		if (yyaccept <= 5) {
			if (yyaccept == 4) goto yy70;
			else goto yy76;
		} else {
			goto yy80;
		}
	}
yy43:
	++cur;
#line 149 "tokenizer.re"
	{ RET(TK_STRING) }
#line 492 "tokenizer.c"
yy44:
	yych = *++cur;
	if (yybm[0+yych] & 128) goto yy44;
yy45:
#line 144 "tokenizer.re"
	{ RET(TK_REGISTER) }
#line 499 "tokenizer.c"
yy46:
	yych = *++cur;
	if (yych <= 'Z') {
		if (yych <= '/') goto yy45;
		if (yych <= '9') goto yy46;
		if (yych <= '@') goto yy45;
		goto yy46;
	} else {
		if (yych <= '_') {
			if (yych <= '^') goto yy45;
			goto yy46;
		} else {
			if (yych <= '`') goto yy45;
			if (yych <= 'z') goto yy46;
			goto yy45;
		}
	}
yy47:
	++cur;
#line 140 "tokenizer.re"
	{ RET(TK_ARROW) }
#line 521 "tokenizer.c"
yy48:
	yyaccept = 2;
	yych = *(mar = ++cur);
	if (yych <= 'C') {
		if (yych <= '/') goto yy49;
		if (yych <= '9') goto yy48;
	} else {
		if (yych <= 'E') goto yy53;
		if (yych <= 'c') goto yy49;
		if (yych <= 'e') goto yy53;
	}
yy49:
#line 148 "tokenizer.re"
	{ RET(TK_REAL) }
#line 536 "tokenizer.c"
yy50:
	++cur;
#line 139 "tokenizer.re"
	{ RET(TK_COMMENT) }
#line 541 "tokenizer.c"
yy51:
	yych = *++cur;
	if (yych <= '\v') {
		if (yych == '\t') goto yy51;
		if (yych >= '\v') goto yy51;
	} else {
		if (yych <= '\r') {
			if (yych >= '\r') goto yy51;
		} else {
			if (yych == ' ') goto yy51;
		}
	}
	cur = ctxmar;
#line 146 "tokenizer.re"
	{ RET(TK_INTEGER) }
#line 557 "tokenizer.c"
yy52:
	yych = *++cur;
	if (yych <= '-') {
		if (yych <= '\v') {
			if (yych == '\t') {
				ctxmar = cur;
				goto yy51;
			}
			if (yych <= '\n') goto yy42;
			ctxmar = cur;
			goto yy51;
		} else {
			if (yych <= '\r') {
				if (yych <= '\f') goto yy42;
				ctxmar = cur;
				goto yy51;
			} else {
				if (yych == ' ') {
					ctxmar = cur;
					goto yy51;
				}
				goto yy42;
			}
		}
	} else {
		if (yych <= 'E') {
			if (yych <= '/') {
				if (yych <= '.') goto yy48;
				goto yy42;
			} else {
				if (yych <= '9') goto yy52;
				if (yych <= 'C') goto yy42;
			}
		} else {
			if (yych <= 'e') {
				if (yych <= 'c') goto yy42;
			} else {
				if (yych == 'x') goto yy54;
				goto yy42;
			}
		}
	}
yy53:
	yych = *++cur;
	if (yych <= ',') {
		if (yych == '+') goto yy62;
		goto yy42;
	} else {
		if (yych <= '-') goto yy62;
		if (yych <= '/') goto yy42;
		if (yych <= '9') goto yy63;
		goto yy42;
	}
yy54:
	yyaccept = 3;
	yych = *(mar = ++cur);
	if (yych <= '/') goto yy55;
	if (yych <= '9') goto yy64;
	if (yych == '?') goto yy65;
yy55:
#line 147 "tokenizer.re"
	{ RET(TK_TYPE_DIM) }
#line 620 "tokenizer.c"
yy56:
	yych = *++cur;
	if (yych <= 'Z') {
		if (yych <= '/') goto yy57;
		if (yych <= '9') goto yy56;
		if (yych >= 'A') goto yy56;
	} else {
		if (yych <= '_') {
			if (yych >= '_') goto yy56;
		} else {
			if (yych <= '`') goto yy57;
			if (yych <= 'z') goto yy56;
		}
	}
yy57:
#line 145 "tokenizer.re"
	{ RET(TK_FUNCTION_NAME) }
#line 638 "tokenizer.c"
yy58:
	yych = *++cur;
	if (yych <= '^') {
		if (yych <= '@') goto yy42;
		if (yych <= 'Z') goto yy66;
		goto yy42;
	} else {
		if (yych == '`') goto yy42;
		if (yych <= 'z') goto yy66;
		goto yy42;
	}
yy59:
	yyaccept = 1;
	yych = *(mar = ++cur);
	if (yych == 'S') goto yy68;
	if (yych == 's') goto yy68;
	goto yy32;
yy60:
	yyaccept = 1;
	yych = *(mar = ++cur);
	if (yych == 'L') goto yy69;
	if (yych == 'l') goto yy69;
	goto yy32;
yy61:
	yyaccept = 1;
	yych = *(mar = ++cur);
	if (yych == 'I') goto yy71;
	if (yych == 'i') goto yy71;
	goto yy32;
yy62:
	yych = *++cur;
	if (yych <= '/') goto yy42;
	if (yych >= ':') goto yy42;
yy63:
	yych = *++cur;
	if (yych <= '/') goto yy49;
	if (yych <= '9') goto yy63;
	goto yy49;
yy64:
	yych = *++cur;
	if (yych <= '/') goto yy42;
	if (yych <= '9') goto yy64;
	if (yych == 'x') goto yy54;
	goto yy42;
yy65:
	yych = *++cur;
	if (yych == 'x') goto yy54;
	goto yy42;
yy66:
	yych = *++cur;
	if (yych <= 'Z') {
		if (yych <= '/') goto yy67;
		if (yych <= '9') goto yy66;
		if (yych >= 'A') goto yy66;
	} else {
		if (yych <= '_') {
			if (yych >= '_') goto yy66;
		} else {
			if (yych <= '`') goto yy67;
			if (yych <= 'z') goto yy66;
		}
	}
yy67:
#line 143 "tokenizer.re"
	{ RET(TK_NAME_DOT_NAME) }
#line 704 "tokenizer.c"
yy68:
	yyaccept = 1;
	yych = *(mar = ++cur);
	if (yych == 'T') goto yy72;
	if (yych == 't') goto yy72;
	goto yy32;
yy69:
	yyaccept = 4;
	yych = *(mar = ++cur);
	if (yybm[0+yych] & 32) goto yy31;
	if (yych == '.') goto yy58;
yy70:
#line 109 "tokenizer.re"
	{ RET(KW_ALL) }
#line 719 "tokenizer.c"
yy71:
	yyaccept = 1;
	yych = *(mar = ++cur);
	if (yych == 'T') goto yy73;
	if (yych == 't') goto yy73;
	goto yy32;
yy72:
	yyaccept = 1;
	yych = *(mar = ++cur);
	if (yych == 'R') goto yy74;
	if (yych == 'r') goto yy74;
	goto yy32;
yy73:
	yyaccept = 1;
	yych = *(mar = ++cur);
	if (yych == 'E') goto yy75;
	if (yych == 'e') goto yy75;
	goto yy32;
yy74:
	yyaccept = 1;
	yych = *(mar = ++cur);
	if (yych == 'A') goto yy77;
	if (yych == 'a') goto yy77;
	goto yy32;
yy75:
	yyaccept = 5;
	yych = *(mar = ++cur);
	if (yybm[0+yych] & 32) goto yy31;
	if (yych == '.') goto yy58;
yy76:
#line 110 "tokenizer.re"
	{ RET(KW_WRITE) }
#line 752 "tokenizer.c"
yy77:
	yyaccept = 1;
	yych = *(mar = ++cur);
	if (yych == 'C') goto yy78;
	if (yych != 'c') goto yy32;
yy78:
	yyaccept = 1;
	yych = *(mar = ++cur);
	if (yych == 'T') goto yy79;
	if (yych != 't') goto yy32;
yy79:
	yyaccept = 6;
	yych = *(mar = ++cur);
	if (yybm[0+yych] & 32) goto yy31;
	if (yych == '.') goto yy58;
yy80:
#line 108 "tokenizer.re"
	{ RET(KW_ABSTRACT) }
#line 771 "tokenizer.c"
}
#line 150 "tokenizer.re"

    }
}
