/* Generated by re2c 4.0.1 */
#line 1 "tokenizer.re"
// Compile with:
// re2c --no-generation-date -b tokenizer.re -o tokenizer.c

#include <stdbool.h>

#include "tokenizer.h"


#define RET(x) \
    *token_type=x; \
    *position = cur-string; \
    return;

void tokenizer_get_next_token(const unsigned char *string,
        uint64_t *position, TokenType *token_type)
{
    const unsigned char *cur = string + *position;
    while (true) {
        /*
        Re2c has excellent documentation at:

        https://re2c.org/manual/manual_c.html

        The first paragraph there explains the basics:

        * If multiple rules match, the longest match takes precedence
        * If multiple rules match the same string, the earlier rule takes
          precedence
        * Default rule `*` should always be defined, it has the lowest priority
          regardless of its place and matches any code unit
        * We use the "Sentinel character" method for end of input:
            * The end of the input text is denoted with a null character \x00
            * Thus the null character cannot be part of the input otherwise
            * There is one rule to match \x00 to end the parser
            * No other rule is allowed to match \x00, otherwise the re2c block
              would parse past the end of the string and segfaults
            * A special case of the previous point are negated character
              ranges, such as [^"\x00], where one must include \x00 in it to
              ensure this rule does not match \x00 (all other rules simply do
              not mention \x00)
            * See the "Handling the end of input" section in the re2c
              documentation for more info

        The re2c block interacts with the rest of the code via just one pointer
        variable `cur`. On entering the re2c block, the `cur` variable must
        point to the first character of the token to be tokenized by the block.
        The re2c block below then executes on its own until a rule is matched:
        the action in {} is then executed. In that action `cur` points to the
        first character of the next token.

        Before the re2c block we save the current `cur` into `tok`, so that we
        can use `tok` and `cur` in the action in {} to extract the token that
        corresponds to the rule that got matched:

        * `tok` points to the first character of the token
        * `cur-1` points to the last character of the token
        * `cur` points to the first character of the next token
        * `cur-tok` is the length of the token

        In the action, we do one of:

        * call `continue` which executes another cycle in the for loop (which
          will parse the next token); we use this to skip a token
        * call `return` which returns from this function; we return a token

        In both cases, `cur` points to first character of the next
        token, which becomes `tok` at the next iteration of the loop (either
        right away after `continue` or after the `lex` function is called again
        after `return`).

        See the manual for more details.
        */


        // These two variables are needed by the re2c block below internally,
        // initialization is not needed. One can think of them as local
        // variables of the re2c block.
        const unsigned char *mar; //, *ctxmar;
        
#line 83 "tokenizer.c"
{
	unsigned char yych;
	unsigned int yyaccept = 0;
	static const unsigned char yybm[256] = {
		  0, 128, 128, 128, 128, 128, 128, 128,
		128, 144, 128, 144, 128, 144, 128, 128,
		128, 128, 128, 128, 128, 128, 128, 128,
		128, 128, 128, 128, 128, 128, 128, 128,
		144, 128,   0, 128, 128, 128, 128, 128,
		128, 128, 128, 128, 128, 128, 128, 128,
		224, 224, 224, 224, 224, 224, 224, 224,
		224, 224, 128, 128, 128, 128, 128, 128,
		128, 192, 192, 192, 192, 192, 192, 192,
		192, 192, 192, 192, 192, 192, 192, 192,
		192, 192, 192, 192, 192, 192, 192, 192,
		192, 192, 192, 128, 128, 128, 128, 192,
		128, 192, 192, 192, 192, 192, 192, 192,
		192, 192, 192, 192, 192, 192, 192, 192,
		192, 192, 192, 192, 192, 192, 192, 192,
		192, 192, 192, 128, 128, 128, 128, 128,
		128, 128, 128, 128, 128, 128, 128, 128,
		128, 128, 128, 128, 128, 128, 128, 128,
		128, 128, 128, 128, 128, 128, 128, 128,
		128, 128, 128, 128, 128, 128, 128, 128,
		128, 128, 128, 128, 128, 128, 128, 128,
		128, 128, 128, 128, 128, 128, 128, 128,
		128, 128, 128, 128, 128, 128, 128, 128,
		128, 128, 128, 128, 128, 128, 128, 128,
		128, 128, 128, 128, 128, 128, 128, 128,
		128, 128, 128, 128, 128, 128, 128, 128,
		128, 128, 128, 128, 128, 128, 128, 128,
		128, 128, 128, 128, 128, 128, 128, 128,
		128, 128, 128, 128, 128, 128, 128, 128,
		128, 128, 128, 128, 128, 128, 128, 128,
		128, 128, 128, 128, 128, 128, 128, 128,
		128, 128, 128, 128, 128, 128, 128, 128
	};
	yych = *cur;
	if (yybm[0+yych] & 16) goto yy4;
	switch (yych) {
		case 0x00: goto yy1;
		case '\t':
		case '\n': goto yy5;
		case ' ':
		case '!': goto yy6;
		case '"': goto yy7;
		case '#': goto yy8;
		case '$': goto yy9;
		case '%': goto yy10;
		case '(': goto yy12;
		case ')': goto yy13;
		case '*': goto yy14;
		case '+': goto yy15;
		case ',': goto yy16;
		case '-': goto yy17;
		case '.': goto yy18;
		case '/': goto yy20;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy21;
		case ':': goto yy23;
		case ';': goto yy24;
		case '<': goto yy25;
		case '=': goto yy26;
		case '>': goto yy27;
		case '@': goto yy28;
		case 'A':
		case 'a': goto yy30;
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'x':
		case 'y':
		case 'z': goto yy32;
		case 'W':
		case 'w': goto yy34;
		case '[': goto yy35;
		case ']': goto yy36;
		case '^': goto yy37;
		case '{': goto yy38;
		case '|': goto yy39;
		case '}': goto yy40;
		default: goto yy2;
	}
yy1:
	++cur;
#line 103 "tokenizer.re"
	{ RET(TK_EOF) }
#line 222 "tokenizer.c"
yy2:
	++cur;
yy3:
#line 102 "tokenizer.re"
	{ RET(TK_ERROR) }
#line 228 "tokenizer.c"
yy4:
	yych = *++cur;
	if (yybm[0+yych] & 16) goto yy4;
#line 104 "tokenizer.re"
	{ RET(TK_WHITESPACE) }
#line 234 "tokenizer.c"
yy5:
	++cur;
#line 105 "tokenizer.re"
	{ RET(TK_NEWLINE) }
#line 239 "tokenizer.c"
yy6:
	++cur;
#line 122 "tokenizer.re"
	{ RET(TK_EXCLAMATION) }
#line 244 "tokenizer.c"
yy7:
	yyaccept = 0;
	yych = *(mar = ++cur);
	if (yych <= 0x00) goto yy3;
	goto yy42;
yy8:
	yych = *++cur;
	if (yych <= '^') {
		if (yych <= '@') goto yy3;
		if (yych <= 'Z') goto yy45;
		goto yy3;
	} else {
		if (yych == '`') goto yy3;
		if (yych <= 'z') goto yy45;
		goto yy3;
	}
yy9:
	++cur;
#line 123 "tokenizer.re"
	{ RET(TK_DOLLAR) }
#line 265 "tokenizer.c"
yy10:
	yych = *++cur;
	if (yych <= 'Z') {
		if (yych <= '/') goto yy11;
		if (yych <= '9') goto yy47;
		if (yych >= 'A') goto yy49;
	} else {
		if (yych <= '_') {
			if (yych >= '_') goto yy49;
		} else {
			if (yych <= '`') goto yy11;
			if (yych <= 'z') goto yy49;
		}
	}
yy11:
#line 130 "tokenizer.re"
	{ RET(TK_PERCENT) }
#line 283 "tokenizer.c"
yy12:
	++cur;
#line 113 "tokenizer.re"
	{ RET(TK_LPAREN) }
#line 288 "tokenizer.c"
yy13:
	++cur;
#line 114 "tokenizer.re"
	{ RET(TK_RPAREN) }
#line 293 "tokenizer.c"
yy14:
	++cur;
#line 132 "tokenizer.re"
	{ RET(TK_STAR) }
#line 298 "tokenizer.c"
yy15:
	++cur;
#line 124 "tokenizer.re"
	{ RET(TK_PLUS) }
#line 303 "tokenizer.c"
yy16:
	++cur;
#line 131 "tokenizer.re"
	{ RET(TK_COMMA) }
#line 308 "tokenizer.c"
yy17:
	yych = *++cur;
	if (yych == '>') goto yy50;
#line 125 "tokenizer.re"
	{ RET(TK_MINUS) }
#line 314 "tokenizer.c"
yy18:
	yych = *++cur;
	if (yych <= '/') goto yy19;
	if (yych <= '9') goto yy51;
yy19:
#line 136 "tokenizer.re"
	{ RET(TK_DOT) }
#line 322 "tokenizer.c"
yy20:
	yych = *++cur;
	if (yych == '/') goto yy53;
#line 129 "tokenizer.re"
	{ RET(TK_SLASH) }
#line 328 "tokenizer.c"
yy21:
	yyaccept = 1;
	yych = *(mar = ++cur);
	if (yybm[0+yych] & 32) goto yy21;
	if (yych <= 'E') {
		if (yych == '.') goto yy51;
		if (yych >= 'D') goto yy54;
	} else {
		if (yych <= 'e') {
			if (yych >= 'd') goto yy54;
		} else {
			if (yych == 'x') goto yy55;
		}
	}
yy22:
#line 148 "tokenizer.re"
	{ RET(TK_INTEGER) }
#line 346 "tokenizer.c"
yy23:
	++cur;
#line 127 "tokenizer.re"
	{ RET(TK_COLON) }
#line 351 "tokenizer.c"
yy24:
	++cur;
#line 128 "tokenizer.re"
	{ RET(TK_SEMICOLON) }
#line 356 "tokenizer.c"
yy25:
	++cur;
#line 120 "tokenizer.re"
	{ RET(TK_LANGLE) }
#line 361 "tokenizer.c"
yy26:
	++cur;
#line 126 "tokenizer.re"
	{ RET(TK_EQUAL) }
#line 366 "tokenizer.c"
yy27:
	++cur;
#line 121 "tokenizer.re"
	{ RET(TK_RANGLE) }
#line 371 "tokenizer.c"
yy28:
	yych = *++cur;
	if (yych <= '^') {
		if (yych <= '@') goto yy29;
		if (yych <= 'Z') goto yy57;
	} else {
		if (yych == '`') goto yy29;
		if (yych <= 'z') goto yy57;
	}
yy29:
#line 134 "tokenizer.re"
	{ RET(TK_AT) }
#line 384 "tokenizer.c"
yy30:
	yyaccept = 2;
	yych = *(mar = ++cur);
	if (yych <= 'L') {
		if (yych == 'B') goto yy60;
		if (yych <= 'K') goto yy33;
		goto yy61;
	} else {
		if (yych <= 'b') {
			if (yych <= 'a') goto yy33;
			goto yy60;
		} else {
			if (yych == 'l') goto yy61;
			goto yy33;
		}
	}
yy31:
#line 144 "tokenizer.re"
	{ RET(TK_NAME) }
#line 404 "tokenizer.c"
yy32:
	yyaccept = 2;
	yych = *(mar = ++cur);
yy33:
	if (yybm[0+yych] & 64) goto yy32;
	if (yych == '.') goto yy59;
	goto yy31;
yy34:
	yyaccept = 2;
	yych = *(mar = ++cur);
	if (yych == 'R') goto yy62;
	if (yych == 'r') goto yy62;
	goto yy33;
yy35:
	++cur;
#line 115 "tokenizer.re"
	{ RET(TK_LBRACKET) }
#line 422 "tokenizer.c"
yy36:
	++cur;
#line 116 "tokenizer.re"
	{ RET(TK_RBRACKET) }
#line 427 "tokenizer.c"
yy37:
	++cur;
#line 135 "tokenizer.re"
	{ RET(TK_CARET) }
#line 432 "tokenizer.c"
yy38:
	yych = *++cur;
	if (yych == '\n') goto yy63;
#line 117 "tokenizer.re"
	{ RET(TK_LBRACE) }
#line 438 "tokenizer.c"
yy39:
	++cur;
#line 133 "tokenizer.re"
	{ RET(TK_VBAR) }
#line 443 "tokenizer.c"
yy40:
	++cur;
#line 119 "tokenizer.re"
	{ RET(TK_RBRACE) }
#line 448 "tokenizer.c"
yy41:
	yych = *++cur;
yy42:
	if (yybm[0+yych] & 128) goto yy41;
	if (yych >= 0x01) goto yy44;
yy43:
	cur = mar;
	if (yyaccept <= 3) {
		if (yyaccept <= 1) {
			if (yyaccept == 0) goto yy3;
			else goto yy22;
		} else {
			if (yyaccept == 2) goto yy31;
			else goto yy52;
		}
	} else {
		if (yyaccept <= 5) {
			if (yyaccept == 4) goto yy56;
			else goto yy72;
		} else {
			if (yyaccept == 6) goto yy78;
			else goto yy82;
		}
	}
yy44:
	++cur;
#line 151 "tokenizer.re"
	{ RET(TK_STRING) }
#line 477 "tokenizer.c"
yy45:
	yych = *++cur;
	if (yych <= 'Z') {
		if (yych <= '/') goto yy46;
		if (yych <= '9') goto yy45;
		if (yych >= 'A') goto yy45;
	} else {
		if (yych <= '_') {
			if (yych >= '_') goto yy45;
		} else {
			if (yych <= '`') goto yy46;
			if (yych <= 'z') goto yy45;
		}
	}
yy46:
#line 142 "tokenizer.re"
	{ RET(TK_HASH_NAME); }
#line 495 "tokenizer.c"
yy47:
	yych = *++cur;
	if (yych <= '/') goto yy48;
	if (yych <= '9') goto yy47;
yy48:
#line 146 "tokenizer.re"
	{ RET(TK_REGISTER) }
#line 503 "tokenizer.c"
yy49:
	yych = *++cur;
	if (yych <= 'Z') {
		if (yych <= '/') goto yy48;
		if (yych <= '9') goto yy49;
		if (yych <= '@') goto yy48;
		goto yy49;
	} else {
		if (yych <= '_') {
			if (yych <= '^') goto yy48;
			goto yy49;
		} else {
			if (yych <= '`') goto yy48;
			if (yych <= 'z') goto yy49;
			goto yy48;
		}
	}
yy50:
	++cur;
#line 140 "tokenizer.re"
	{ RET(TK_ARROW) }
#line 525 "tokenizer.c"
yy51:
	yyaccept = 3;
	yych = *(mar = ++cur);
	if (yych <= 'C') {
		if (yych <= '/') goto yy52;
		if (yych <= '9') goto yy51;
	} else {
		if (yych <= 'E') goto yy54;
		if (yych <= 'c') goto yy52;
		if (yych <= 'e') goto yy54;
	}
yy52:
#line 150 "tokenizer.re"
	{ RET(TK_REAL) }
#line 540 "tokenizer.c"
yy53:
	++cur;
#line 139 "tokenizer.re"
	{ RET(TK_COMMENT) }
#line 545 "tokenizer.c"
yy54:
	yych = *++cur;
	if (yych <= ',') {
		if (yych == '+') goto yy64;
		goto yy43;
	} else {
		if (yych <= '-') goto yy64;
		if (yych <= '/') goto yy43;
		if (yych <= '9') goto yy65;
		goto yy43;
	}
yy55:
	yyaccept = 4;
	yych = *(mar = ++cur);
	if (yych <= '/') goto yy56;
	if (yych <= '9') goto yy66;
	if (yych == '?') goto yy67;
yy56:
#line 149 "tokenizer.re"
	{ RET(TK_TYPE_DIM) }
#line 566 "tokenizer.c"
yy57:
	yych = *++cur;
	if (yych <= 'Z') {
		if (yych <= '/') goto yy58;
		if (yych <= '9') goto yy57;
		if (yych >= 'A') goto yy57;
	} else {
		if (yych <= '_') {
			if (yych >= '_') goto yy57;
		} else {
			if (yych <= '`') goto yy58;
			if (yych <= 'z') goto yy57;
		}
	}
yy58:
#line 147 "tokenizer.re"
	{ RET(TK_FUNCTION_NAME) }
#line 584 "tokenizer.c"
yy59:
	yych = *++cur;
	if (yych <= '^') {
		if (yych <= '@') goto yy43;
		if (yych <= 'Z') goto yy68;
		goto yy43;
	} else {
		if (yych == '`') goto yy43;
		if (yych <= 'z') goto yy68;
		goto yy43;
	}
yy60:
	yyaccept = 2;
	yych = *(mar = ++cur);
	if (yych == 'S') goto yy70;
	if (yych == 's') goto yy70;
	goto yy33;
yy61:
	yyaccept = 2;
	yych = *(mar = ++cur);
	if (yych == 'L') goto yy71;
	if (yych == 'l') goto yy71;
	goto yy33;
yy62:
	yyaccept = 2;
	yych = *(mar = ++cur);
	if (yych == 'I') goto yy73;
	if (yych == 'i') goto yy73;
	goto yy33;
yy63:
	++cur;
	cur -= 1;
#line 118 "tokenizer.re"
	{ RET(TK_LBRACE_END) }
#line 619 "tokenizer.c"
yy64:
	yych = *++cur;
	if (yych <= '/') goto yy43;
	if (yych >= ':') goto yy43;
yy65:
	yych = *++cur;
	if (yych <= '/') goto yy52;
	if (yych <= '9') goto yy65;
	goto yy52;
yy66:
	yych = *++cur;
	if (yych <= '/') goto yy43;
	if (yych <= '9') goto yy66;
	if (yych == 'x') goto yy55;
	goto yy43;
yy67:
	yych = *++cur;
	if (yych == 'x') goto yy55;
	goto yy43;
yy68:
	yych = *++cur;
	if (yych <= 'Z') {
		if (yych <= '/') goto yy69;
		if (yych <= '9') goto yy68;
		if (yych >= 'A') goto yy68;
	} else {
		if (yych <= '_') {
			if (yych >= '_') goto yy68;
		} else {
			if (yych <= '`') goto yy69;
			if (yych <= 'z') goto yy68;
		}
	}
yy69:
#line 145 "tokenizer.re"
	{ RET(TK_NAME_DOT_NAME) }
#line 656 "tokenizer.c"
yy70:
	yyaccept = 2;
	yych = *(mar = ++cur);
	if (yych == 'T') goto yy74;
	if (yych == 't') goto yy74;
	goto yy33;
yy71:
	yyaccept = 5;
	yych = *(mar = ++cur);
	if (yybm[0+yych] & 64) goto yy32;
	if (yych == '.') goto yy59;
yy72:
#line 109 "tokenizer.re"
	{ RET(KW_ALL) }
#line 671 "tokenizer.c"
yy73:
	yyaccept = 2;
	yych = *(mar = ++cur);
	if (yych == 'T') goto yy75;
	if (yych == 't') goto yy75;
	goto yy33;
yy74:
	yyaccept = 2;
	yych = *(mar = ++cur);
	if (yych == 'R') goto yy76;
	if (yych == 'r') goto yy76;
	goto yy33;
yy75:
	yyaccept = 2;
	yych = *(mar = ++cur);
	if (yych == 'E') goto yy77;
	if (yych == 'e') goto yy77;
	goto yy33;
yy76:
	yyaccept = 2;
	yych = *(mar = ++cur);
	if (yych == 'A') goto yy79;
	if (yych == 'a') goto yy79;
	goto yy33;
yy77:
	yyaccept = 6;
	yych = *(mar = ++cur);
	if (yybm[0+yych] & 64) goto yy32;
	if (yych == '.') goto yy59;
yy78:
#line 110 "tokenizer.re"
	{ RET(KW_WRITE) }
#line 704 "tokenizer.c"
yy79:
	yyaccept = 2;
	yych = *(mar = ++cur);
	if (yych == 'C') goto yy80;
	if (yych != 'c') goto yy33;
yy80:
	yyaccept = 2;
	yych = *(mar = ++cur);
	if (yych == 'T') goto yy81;
	if (yych != 't') goto yy33;
yy81:
	yyaccept = 7;
	yych = *(mar = ++cur);
	if (yybm[0+yych] & 64) goto yy32;
	if (yych == '.') goto yy59;
yy82:
#line 108 "tokenizer.re"
	{ RET(KW_ABSTRACT) }
#line 723 "tokenizer.c"
}
#line 152 "tokenizer.re"

    }
}
